version: 2

project_name: wireguard-outline-bridge

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: bridge
    main: ./cmd/bridge
    binary: bridge
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main Dirty={{.IsGitDirty}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}-
      {{- .Arch }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - configs/*.yaml

dockers:
  - id: bridge-linux-amd64
    ids:
      - bridge
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/bigbes/wireguard-outline-bridge:{{ .Version }}-amd64
      - ghcr.io/bigbes/wireguard-outline-bridge:latest-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

docker_manifests:
  - id: bridge-latest
    name_template: ghcr.io/bigbes/wireguard-outline-bridge:{{ .Version }}
    image_templates:
      - ghcr.io/bigbes/wireguard-outline-bridge:{{ .Version }}-amd64
  - id: bridge-version
    name_template: ghcr.io/bigbes/wireguard-outline-bridge:latest
    image_templates:
      - ghcr.io/bigbes/wireguard-outline-bridge:latest-amd64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: bigbes
    name: wireguard-outline-bridge
  draft: false
  prerelease: auto
  mode: replace

checksum:
  name_template: checksums.txt
  algorithm: sha256
